credentials:
  usernames:
    student1:
      email: student1@gmail.com
      name: Test Student
      password: student123
    staff1:
      email: benjamin@chieac.org
      name: Benjamin Drury
      password: chieacstaff123
      role: staff

cookie:
  expiry_days: 30
  key: chieac_secret_key
  name: chieac_cookie

preauthorized:
  emails:
    - benjamin@chieac.org